yatube/posts/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name="group"),
    path('new/', views.new_post, name='new_post'),

    path('follow/', views.follow_index, name="follow"),

    path('users/', views.users_view, name="users"),
    path("users/<str:username>/follow/", views.profile_follow, name="profile_follow"),
    path("users/<str:username>/unfollow/", views.profile_unfollow, name="profile_unfollow"),

    path('users/<str:username>/', views.profile, name='profile'),
    path('users/<str:username>/<int:post_id>/', views.post_view, name='post'),
    path('users/<str:username>/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path("users/<str:username>/<int:post_id>/comment", views.add_comment, name="add_comment"),
]

yatube/yatube/urls.py
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.contrib.flatpages import views
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

from .views import user_contact


urlpatterns = [
    path('', include("posts.urls")),
    path('contact/', user_contact, name='contact'),
    path('about/', include('django.contrib.flatpages.urls')),
    path('auth/', include("users.urls")),
    path('auth/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('about-author/', views.flatpage, {'url': '/about-author/'}, name='about'),
    path('about-spec/', views.flatpage, {'url': '/about-spec/'}, name='terms'),
]

handler404 = "posts.views.page_not_found" # noqa
handler500 = "posts.views.server_error" # noqa

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += (path('__debug__/', include('debug_toolbar.urls')),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import Q, F

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return f"{self.title}"


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(verbose_name="date published", auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="posts")
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, related_name="posts", blank=True, null=True)
    image = models.ImageField(upload_to='posts/', blank=True, null=True)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    text = models.TextField()
    date_created = models.DateTimeField(verbose_name="date created", auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="follower")
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_user_author'
            ),
            models.CheckConstraint(
                check=~Q(user=F('author')),
                name='user_not_author'
            )
        ]

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.decorators.cache import cache_page
from django.core.paginator import Paginator

from .models import Post, Group, Comment, Follow
from .forms import PostForm, CommentForm

User = get_user_model()


def pagination(request, posts, num):
    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return page, paginator


@cache_page(20, key_prefix='index_page')
def index(request):
    posts = list(Post.objects.order_by('-pub_date')
                 .select_related('author', 'group')
                 .prefetch_related('comments')
                 )
    page, paginator = pagination(request, posts, 10)
    return render(request, 'index.html', {'page': page,
                                          'paginator': paginator,
                                          'title': 'Последние обновления на сайте',
                                          'index': True
                                          })


@cache_page(29, key_prefix='users_page')
def users_view(request):
    authors = list(User.objects.all())
    return render(request, 'index.html', {'authors': authors, 'title': 'Список авторов'})


@cache_page(20, key_prefix='group_page')
def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = list(Post.objects.filter(group=group)
                 .select_related('author', 'group')
                 .order_by('-pub_date')
                 .prefetch_related('comments')
                 )
    page, paginator = pagination(request, posts, 10)
    return render(request, 'group.html', {'group': group, 'page': page, 'paginator': paginator})


@login_required(redirect_field_name='login')
def new_post(request):
    title = 'Новая запись'
    button = 'Добавить'
    if request.method == 'POST':
        form = PostForm(request.POST or None, files=request.FILES or None)
        if form.is_valid():
            post = form.save(commit=False)
            user = request.user
            post.author = user
            post.save()
            return redirect('post', user, post.id)

        return render(request, 'new_post.html', {'form': form, 'title': title, 'button': button})

    form = PostForm()
    return render(request, 'new_post.html', {'form': form, 'title': title, 'button': button})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    following = Follow.objects.filter(user=request.user, author=author)
    posts = list(Post.objects.filter(author=author)
                 .select_related('author', 'group')
                 .prefetch_related('comments')
                 .order_by('-pub_date')
                 )
    page, paginator = pagination(request, posts, 10)
    posts_count = len(posts)
    return render(request, 'profile.html', {'page': page,
                                            'paginator': paginator,
                                            'author': author,
                                            'count': posts_count,
                                            'following': following,
                                            })


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, author=author, id=post_id)
    comments = list(Comment.objects.filter(post=post))
    posts_count = Post.objects.filter(author=author).count()
    return render(request, 'profile.html', {'author': author, 'post': post, 'count': posts_count, 'items': comments})


@login_required(redirect_field_name='login')
def post_edit(request, username, post_id):
    if username == request.user.username:
        post = get_object_or_404(Post, author__username=username, id=post_id)
        if request.method == 'POST':
            form = PostForm(request.POST or None, files=request.FILES or None, instance=post)
            if form.is_valid():
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                return redirect('post', username, post.id)

            return render(request, 'new_post.html', {'form': form,
                                                     'title': 'Редактировать запись',
                                                     'button': 'Сохранить',
                                                     'username': username,
                                                     'post_id': post_id
                                                     })

        form = PostForm(instance=post)
        return render(request, 'new_post.html', {'form': form,
                                                 'title': 'Редактировать запись',
                                                 'button': 'Сохранить',
                                                 'username': username,
                                                 'post_id': post_id
                                                 })
    else:
        return redirect('post', username, post_id)


@login_required(redirect_field_name='login')
def add_comment(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('post', author.username, post.id)

        return render(request, 'comments.html', {'form': form})

    form = CommentForm()
    return render(request, 'comments.html', {'form': form})


@cache_page(20, key_prefix='follow_page')
@login_required
def follow_index(request):
    posts = list(Post.objects.filter(author__following__user=request.user)
                 .select_related('author', 'group')
                 .order_by('-pub_date')
                 .prefetch_related('comments')
                 )
    page, paginator = pagination(request, posts, 10)
    return render(request, 'index.html', {'page': page,
                                          'paginator': paginator,
                                          'title': 'Посты избранных авторов',
                                          'follow': True
                                          })


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        if not Follow.objects.filter(user=request.user, author=author):
            follow = Follow.objects.create(user=request.user, author=author)
            follow.save()
    return redirect('profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        author = get_object_or_404(User, username=username)
        follow = get_object_or_404(Follow, user=request.user, author=author)
        follow.delete()
    return redirect('profile', username)


def page_not_found(request, exception):
    return render(
        request,
        "misc/404.html",
        {"path": request.path},
        status=404
    )


def server_error(request):
    return render(request, "misc/500.html", status=500)

yatube/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    </head>
    <body>
        {% include 'nav.html' %}
        <main>
            <div class="container">
                {% block content %}
                {% endblock content %}
            </div>
        </main>
        {% include 'footer.html' %}
    </body>
</html>

yatube/templates/comments.html
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
<form action="{% url 'add_comment' post.author.username post.id %}"
    method="post">
    {% csrf_token %}
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
    <form>
        <div class="form-group">
            <label for="{{ form.text.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ form.text.label }}</label>
            <textarea type="text" class="form-control" name="text" id="id_text"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
    </form>
    </div>
</form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in items %}
<div class="media mb-4">
<div class="media-body">
    <h5 class="mt-0">
    <a href="{% url 'profile' item.author.username %}"
        name="comment_{{ item.id }}"
        >{{ item.author.username }}</a>
    </h5>
    {{ item.text }}
</div>
</div>

{% endfor %}

yatube/templates/contact.html
{% extends "base.html" %}

{% block title %}Отправить письмо{% endblock %}

{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">Отправить письмо</div>
      <div class="card-body">
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          Вы ввели данные неправильно.
        </div>
        {% endif %}

        <form method="post" action="{% url 'contact' %}">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}">

            {% for field in form %}
              <div class="form-group row">
                  <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}</label>
                  <div class="col-md-6">
                      {{ field|add_class:"form-control" }}
                  </div>
              </div>
            {% endfor %}

          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Отправить
              </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
        <p class="m-0 text-dark text-center "><a href="/about-author/">Об авторе</a> - <a href="/about-spec/">Технологии</a></p>
        <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/group.html
{% extends "base.html" %}

{% block title %}Записи сообщества {{ group.title }} | Yatube{% endblock %}

{% block header %}Записи сообщества {{ group.title }} | Yatube{% endblock %}

{% block content %}
    <h1>{{ group.title }}</h1>
    <h5>{{ group.description }}</h5>
    {% for post in page %}
        {% include 'post.html' with post=post %}
    {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}

    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator %}
    {% endif %}

{% endblock %}

yatube/templates/index.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    {% include 'menu.html' with what_page=what_page %}

    <h1>{{ title }}</h1>
    {% if authors %}
        {% for author in authors %}
            <div class="card mb-3 mt-1 shadow-sm">
                <div class="card-body">
                        <p class="card-text">
                            <a href="{% url 'profile' author.username %}">
                                <strong class="d-block text-gray-dark">@{{ author.username }}</strong>
                            </a>
                            {{ author.get_full_name }}
                        </p>
                </div>
            </div>
        {% endfor %}
    {% endif %}

    {% for post in page %}
        {% include 'post.html' with post=post %}
    {% endfor %}



    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator %}
    {% endif %}

{% endblock %}

yatube/templates/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'index' %}">Все посты</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'follow' %}">Избранные авторы</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if authors %}active{% endif %}" href="{% url 'users' %}">Список авторов</a>
        </li>
    </ul>
</div>
{% endif %}

yatube/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'profile' username=user.username %}">Пользователь: {{ user.username }}.</a>
            <a class="p-2 text-dark" href="{% url 'new_post' %}">Добавить пост</a>
            <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
            {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

yatube/templates/new_post.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">{{ title }}</div>
      <div class="card-body">
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          Вы ввели данные неправильно.
        </div>
        {% endif %}

        <form method="post" action="{% if post_id %}
                                        {% url 'post_edit' username=user.username post_id=post_id %}
                                    {% else %}
                                        {% url 'new_post' %}
                                    {% endif %}"
        enctype="multipart/form-data">
          {% csrf_token %}
          <input type="hidden" name="next" value="{{ next }}">

            <div class="form-group row">
                <label for="{{ from.text.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ form.text.label }}</label>
                <div class="col-md-6">
                    {{ form.text|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group row">
                <label for="{{ form.group.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ form.group.label }}</label>
                <div class="col-md-6">
                    {{ form.group|add_class:"form-control" }}
                </div>
            </div>

            <div class="form-group row">
                <label for="{{ form.image.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ form.image.label }}</label>
                <div class="col-md-6">
                    {{ form.image|add_class:"form-control" }}
                </div>
            </div>

          <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                  {{ button }}
              </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

yatube/templates/paginator.html
<nav aria-label="Переключение страниц">
    <ul class="pagination">
        {% if items.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ items.previous_page_number }}">&laquo; Предыдущая</a></li>
        {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo; Предыдущая</a></li>
        {% endif %}

        {% for i in paginator.page_range %}
                {% if items.number == i %}
                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(текущая)</span></span></li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
        {% endfor %}

        {% if items.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ items.next_page_number }}">Следующая &raquo;</a></li>
        {% else %}
                <li class="page-item disabled"><a class="page-link" href="#" tabindex="-1" aria-disabled="true">Следующая &raquo;</a></li>
        {% endif %}
    </ul>
</nav>

yatube/templates/post.html
<div class="card mb-3 mt-1 shadow-sm">

    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    <div class="card-body">
        <p class="card-text">
            <a name="post_{{ post.id }}" href="{% url 'profile' post.author.username %}">
                <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
            </a>
            {% if post_view %}
                {{ post.text|linebreaksbr }}
            {% else %}
                {{ post.text|linebreaksbr|truncatewords:50 }}
            {% endif %}
        </p>

        {% if post.group %}
        <a class="card-link muted" href="{% url 'group' post.group.slug %}">
                <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
        </a>
        {% endif %}

        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">
                <a class="btn btn-sm text-muted" href="{% url 'post' post.author.username post.id %}" role="button">
                    {% if post.comments.exists %}
                        {{ post.comments.count }} комментариев
                    {% else%}
                        Добавить комментарий
                    {% endif %}
                </a>

                 {% if user == post.author %}
                 <a class="btn btn-sm text-muted" href="{% url 'post_edit' post.author.username post.id %}"
                        role="button">
                        Редактировать
                </a>
                {% endif %}
            </div>

            <small class="text-muted">{{ post.pub_date }}</small>
        </div>
    </div>
</div>

yatube/templates/profile.html
{% extends "base.html" %}

{% block title %}Профиль автора | {{ author.username }}{% endblock %}

{% block header %}Профиль автора | {{ author.username }}{% endblock %}

{% load user_filters %}

{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                    <div class="card">
                            <div class="card-body">
                                    <div class="h2">
                                        {{ author.get_full_name }}
                                    </div>
                                    <div class="h3 text-muted">
                                         {{ author.username }}
                                    </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                            Подписчиков: {{ author.following.count }} <br/>
                                            Подписан: {{ author.follower.count }}
                                            </div>
                                    </li>
                                    <li class="list-group-item">
                                            <div class="h6 text-muted">
                                                Записей: {{ count }}
                                            </div>
                                    </li>
                                {% if author != request.user %}

                                    <li class="list-group-item">
                                            {% if following %}
                                                <a class="btn btn-lg btn-light"
                                                        href="{% url 'profile_unfollow' author.username %}" role="button">
                                                        Отписаться
                                                </a>
                                            {% else %}
                                                <a class="btn btn-lg btn-primary"
                                                        href="{% url 'profile_follow' author.username %}" role="button">
                                                Подписаться
                                                </a>
                                            {% endif %}
                                    </li>
                                {% endif %}
                            </ul>
                    </div>
            </div>

            <div class="col-md-9">
                    {% if page %}
                        {% for post in page %}
                            {% include 'post.html' with post=post %}
                        {% endfor %}
                    {% else %}
                        {% if post%}
                            {% include 'post.html' with post=post post_view=True %}
                            {% include 'comments.html' %}
                        {% endif %}
                    {% endif %}

                {% if page.has_other_pages %}
                    {% include "paginator.html" with items=page paginator=paginator %}
                {% endif %}
     </div>
    </div>
</main>
{% endblock %}

yatube/templates/thank_you.html
{% extends "base.html" %}
{% block title %}Письмо отправлено{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Письмо отправлено</div>
            <div class="card-body">
                <p>Спасибо что стараетесь сделать проект лучше!</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}